[package]
name = "pest-language-server"
description = "A language server for Pest."
authors = ["Jamalam <james@jamalam.tech>"]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/pest-parser/pest-ide-tools"
license = "Apache-2.0"
license-file = "../LICENSE"
readme = "../README.md"
homepage = "https://pest.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
bench = false

[dependencies]
console_error_panic_hook = "0.1"
js-sys = "0.3"
lsp-types = "0.93"
pest = "2.5"
pest_meta = "2.5"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.4"
wasm-bindgen = "0.2"
